package main

import (
	"github.com/nobonobo/spago"
)

// Render ...
func (c *Form) Render() spago.HTML {
	return spago.Tag("body", 
		spago.Tag("div", 			
			spago.A("class", spago.S(`card p-centered`)),
			spago.A("style", spago.S(`max-width: 640px`)),
			spago.Tag("div", 				
				spago.A("class", spago.S(`card-header`)),
				spago.Tag("div", 					
					spago.A("class", spago.S(`card-title h5`)),
					spago.T(`フォームサンプル`),
				),
			),
			spago.Tag("div", 				
				spago.A("class", spago.S(`card-body`)),
				spago.Tag("form", 					
					spago.A("class", spago.S(`form-horizontal`)),
					spago.Event("submit", c.OnSubmit),
					spago.Tag("div", 						
						spago.A("class", spago.S(`form-group`)),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-2 col-sm-12`)),
							spago.Tag("label", 								
								spago.A("class", spago.S(`form-label`)),
								spago.T(`Name`),
							),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-10 col-sm-12`)),
							
							spago.Tag("input", 								
								spago.A("type", spago.S(`text`)),
								spago.A("name", spago.S(`name`)),
								spago.A("class", spago.S(`form-input`)),
							),
						),
					),
					spago.Tag("div", 						
						spago.A("class", spago.S(`form-group`)),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-2 col-sm-12`)),
							spago.Tag("label", 								
								spago.A("class", spago.S(`form-label`)),
								spago.T(`Memo`),
							),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-10 col-sm-12`)),
							spago.Tag("textarea", 								
								spago.A("name", spago.S(`memo`)),
								spago.A("class", spago.S(`form-input`)),
							),
						),
					),
					spago.Tag("div", 						
						spago.A("class", spago.S(`form-group`)),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-2 col-sm-12`)),
							spago.Tag("label", 								
								spago.A("class", spago.S(`form-label`)),
								spago.T(`Options`),
							),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-10 col-sm-12`)),
							spago.Tag("select", 								
								spago.A("class", spago.S(`form-select`)),
								spago.A("name", spago.S(`options`)),
								spago.A("multiple", spago.S(`true`)),
								spago.Tag("option", 
									spago.T(`Choose an option`),
								),
								spago.Tag("option", 
									spago.T(`Slack`),
								),
								spago.Tag("option", 
									spago.T(`Skype`),
								),
								spago.Tag("option", 
									spago.T(`Hipchat`),
								),
							),
						),
					),
					spago.Tag("div", 						
						spago.A("class", spago.S(`form-group`)),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-2 col-sm-12`)),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`col-10 col-sm-12`)),
							spago.Tag("button", 								
								spago.A("class", spago.S(`btn btn-primary`)),
								spago.T(`Submit`),
							),
						),
					),
				),
			),
		),
	)
}
